Styling
Calligre/attendee-web pull request #119
Opened 2017-03-25 21:35 UTC by schneider-clarisse

First couple attempts at restyling, including a new side nav and better conference switcher modal

2017-03-25 23:38 UTC, larajanecka requested changes
The organizer app appears to have some problems, the menu doesn't collapse and there's an error in the console `Cannot read property 'insertRule' of undefined
    at BrandStore.Layout._this.setBranding (Layout.jsx:22)`

2017-03-25 23:38 UTC, larajanecka commented on src/js/pages/attendee/Layout.jsx
> +    ConferenceStore.removeListener('loadedConferences', this.loadedConferences);
gotta remove the listeners for the brand store as well. Memory links are no bueno

2017-03-25 23:38 UTC, larajanecka commented on src/js/pages/attendee/Layout.jsx
> +    Array.prototype.push.apply(items, [
why not `items.push(`? Just wondering the difference here.

2017-03-25 23:38 UTC, larajanecka commented on package.json
> +    "postcss-loader": "^1.3.3",
react-toolbox missing, also might require updating the version of react used

2017-03-26 00:37 UTC, schneider-clarisse commented on package.json
> +    "postcss-loader": "^1.3.3",
(y)

2017-03-26 00:37 UTC, schneider-clarisse commented
Organizer navbar is pinned unless less than a certain width.

2017-03-26 00:42 UTC, schneider-clarisse commented on src/js/pages/attendee/Layout.jsx
> +    Array.prototype.push.apply(items, [
good catch

2017-03-26 00:43 UTC, schneider-clarisse commented on src/js/pages/attendee/Layout.jsx
> +    ConferenceStore.removeListener('loadedConferences', this.loadedConferences);
gg

2017-03-26 00:53 UTC, schneider-clarisse commented
fixes #115 and #100

2017-03-26 02:25 UTC, schneider-clarisse commented
@larajanecka plz check when you have a minute

2017-03-26 02:28 UTC, larajanecka approved these changes

2017-03-26 02:29 UTC, larajanecka commented
lgtm

2017-03-26 03:09 UTC, merged