Linter
Calligre/attendee-web pull request #40
Opened 2016-10-25 00:26 UTC by larajanecka

Adding eslint

2016-10-28 05:22 UTC, StevenLocke requested changes
I think, aside from Home.js being replaced with an old version, this is good.

2016-10-28 05:22 UTC, StevenLocke commented on src/js/pages/Events.jsx
> +    console.log(EventStore.events);
Extra print statement.

2016-10-28 05:22 UTC, StevenLocke commented on src/js/pages/Home.js
> -import React from "react";
This file should remain.

2016-10-28 05:22 UTC, StevenLocke commented on src/js/pages/Home.jsx
> +import React from "react";
This is out of date. Should replace with the old js file.

2016-11-01 05:10 UTC, TheKevJames approved these changes
LGTM but @StevenLocke should approve this too.

2016-11-01 05:14 UTC, StevenLocke commented on package.json
> +    "immutable": "^3.8.1",
I don't think this is still necessary.

2016-11-01 05:15 UTC, StevenLocke approved these changes

2016-11-06 02:08 UTC, merged