Link
Calligre/attendee-web pull request #46
Opened 2016-11-07 00:41 UTC by schneider-clarisse

Linking works and stuff

2016-11-08 05:38 UTC, larajanecka requested changes
Can't get this to work.

2016-11-08 05:38 UTC, larajanecka commented on src/js/attendee.client.jsx
> +    localStorage.setItem('redirect_after_login', nextState.location.pathname);
Ohhhh I like this.

2016-11-08 05:38 UTC, larajanecka commented on src/js/pages/attendee/Layout.jsx
> +
This should be removed because AuthService is a singleton so you can get the app wide instance through `import AuthService from AuthService`. Remove this

2016-11-08 05:38 UTC, larajanecka commented on src/js/pages/attendee/Profile.jsx
> +    var p = PeopleStore.people;
bad variable name

2016-11-08 05:38 UTC, larajanecka commented on src/js/util/AuthService.jsx
> +    this.lock = new Auth0Lock(clientId, domain, {auth: {redirect: true}})
Since we're redirecting you should remove the on hide listener below (git wont let me comment on the line, but its lines 25-27)

2016-11-08 05:38 UTC, larajanecka commented on src/js/pages/attendee/Profile.jsx
> +    this.state = {
Should this be in getInitialState?

2016-11-08 05:38 UTC, larajanecka commented on package.json
> +    "react-social-icons": "^2.5.1",
Missing npm package react-bootstrap.

2016-11-08 05:38 UTC, larajanecka commented on src/js/util/AuthService.jsx
> +    this.lock = new Auth0Lock(clientId, domain, {auth: {redirect: true}})
Also, I'm still running into the problem where redirect true is not working. I either redirects to the login page or goes to an invalid url.

2016-11-13 08:08 UTC, ericljpemberton commented on src/js/util/AuthService.jsx
> +    if (authResult.state.includes('linking')) {
Attempting to run on this branch as master wasn't working for me. 
I get an error here: "Cannot read property 'includes' of undefined"
Where is authResult.state defined?

2016-11-13 19:20 UTC, schneider-clarisse commented on src/js/pages/attendee/Layout.jsx
> +
(y)

2016-11-13 19:20 UTC, schneider-clarisse commented on src/js/attendee.client.jsx
> +    localStorage.setItem('redirect_after_login', nextState.location.pathname);
*bows*

2016-11-13 19:21 UTC, schneider-clarisse commented on src/js/pages/attendee/Profile.jsx
> +    var p = PeopleStore.people;
also useless

2016-11-13 19:29 UTC, schneider-clarisse commented on package.json
> +    "react-social-icons": "^2.5.1",
(y)

2016-11-13 19:30 UTC, schneider-clarisse commented on src/js/pages/attendee/Profile.jsx
> +    this.state = {
need more context

2016-11-15 05:19 UTC, schneider-clarisse commented on src/js/pages/attendee/Profile.jsx
> +    this.state = {
Chatted offline, this is good to go

2016-11-15 17:46 UTC, TheKevJames commented on src/js/pages/attendee/Profile.jsx
> +      return profile.id == 1;
I think we want this to be `id` rather than hardcoding id 1?

2016-11-16 05:59 UTC, schneider-clarisse commented on src/js/pages/attendee/Profile.jsx
> +      return profile.id == 1;
![image](https://cloud.githubusercontent.com/assets/3297029/20336435/d4aabf0e-ab7e-11e6-904d-799e953e19cc.png)

2016-11-16 06:14 UTC, TheKevJames commented on src/js/pages/attendee/Profile.jsx
> +      return profile.id == 1;
^ that took me forever to understand, had to read through BuzzFeed's top 33 gifs that would make you laugh until you cried.

2016-11-16 07:31 UTC, larajanecka commented on src/js/pages/attendee/Home.jsx
> +      return (<div></div>)
This looks really weird. Is this actually how its done?

2016-11-16 07:37 UTC, schneider-clarisse commented on src/js/pages/attendee/Home.jsx
> +      return (<div></div>)
I'm not allowed to return null, so yea. AFAIK.

2016-11-20 01:43 UTC, larajanecka approved these changes

2016-11-20 22:25 UTC, merged