Organizer
Calligre/attendee-web pull request #47
Opened 2016-11-20 01:42 UTC by larajanecka

Adding the base pages for the organizer app.

@Calligre/frontend

2017-02-10 22:05 UTC, schneider-clarisse requested changes
lgtm when the styling is separated

2017-02-10 22:05 UTC, schneider-clarisse commented on .eslintrc.json
> +        //These rules are in place because eslint import resolver webpack refuses to do its job
lol

2017-02-10 22:05 UTC, schneider-clarisse commented on src/js/organizer.client.jsx
> +  // if (!AuthService.loggedIn()) {
are we planning on doing something with this later? if not take out

2017-02-10 22:05 UTC, schneider-clarisse commented on src/js/pages/organizer/Layout.jsx
> +    const containerStyle = {
I'm a fan of using stylesheets. Could you start a sass file?

2017-02-10 22:05 UTC, schneider-clarisse commented on src/js/pages/organizer/Layout.jsx
> +
remove unnecessary whitespace

2017-02-10 22:17 UTC, larajanecka commented on src/js/organizer.client.jsx
> +  // if (!AuthService.loggedIn()) {
This was just commented out so that Steven can do shit. I'll add it back in.

2017-02-10 22:30 UTC, larajanecka commented on src/js/pages/organizer/Layout.jsx
> +
addressed in 19b177f

2017-02-10 22:31 UTC, larajanecka commented on src/js/pages/organizer/Layout.jsx
> +    const containerStyle = {
addressed in 19b177f

2017-02-10 22:31 UTC, larajanecka commented on src/js/organizer.client.jsx
> +  // if (!AuthService.loggedIn()) {
Addressed in 	85217b6

2017-02-10 22:31 UTC, larajanecka commented on .eslintrc.json
> +        //These rules are in place because eslint import resolver webpack refuses to do its job
sometimes you must admit defeat, I have indeed been bested by webpack and I am unashamed.

2017-03-08 20:09 UTC, ericljpemberton commented on src/js/organizer.client.jsx
>  ReactDOM.render(
@larajanecka is there a reason this rerouting differs so much from the attendee app?

2017-03-08 20:17 UTC, schneider-clarisse approved these changes
lgtm but maybe answer @ericljpemberton first?

2017-03-08 20:58 UTC, larajanecka commented on src/js/organizer.client.jsx
>  ReactDOM.render(
Addressed in 	c0523d5

Also, fixed the console error

2017-03-08 21:00 UTC, merged