Cache viewed notifications in local storage
Calligre/attendee-web pull request #70
Opened 2017-03-09 05:50 UTC by ericljpemberton

Stop users from getting bombarded with messages each time they use the app...

I guess there isn't an easy way for this to work devices? i.e. at the account level?

### Test

Would like to test with more than one notification... Anyone have the POST handy for notifications?

2017-03-09 05:50 UTC, ericljpemberton commented
@schneider-clarisse take a look when you have a minute?

2017-03-09 05:59 UTC, schneider-clarisse requested changes
lgtm other than double parsing

2017-03-09 05:59 UTC, schneider-clarisse commented on src/js/stores/NotificationStore.jsx
> +    let viewedNotifications = JSON.parse(localStorage.getItem("viewedNotifications"));
do you need to parse it twice?

2017-03-09 22:22 UTC, ericljpemberton commented on src/js/stores/NotificationStore.jsx
> +    let viewedNotifications = JSON.parse(localStorage.getItem("viewedNotifications"));
@schneider-clarisse I missed removing the parse from the constructor which is my mistake. We do parse twice in the code. The reasoning I had behind this was that every time we read or want to append to it we should make sure they have the newest version of this list. (They may have it open in multiple chrome windows and keep updating it from these different windows. If that's the case we want to be able to reflect these changes across all windows). 

Although I guess this still wouldn't cover all instances :confused: . I can move it back to the constructor if you think that's better.

2017-03-10 05:57 UTC, schneider-clarisse commented on src/js/stores/NotificationStore.jsx
> +    let viewedNotifications = JSON.parse(localStorage.getItem("viewedNotifications"));
nah that's fine just wanted to double check that there was a true reason

2017-03-10 05:57 UTC, schneider-clarisse approved these changes

2017-03-11 18:37 UTC, larajanecka approved these changes

2017-03-13 23:48 UTC, merged