Organizer events
Calligre/attendee-web pull request #74
Opened 2017-03-13 06:00 UTC by schneider-clarisse

Add the embedded spreadsheet with filtering, sorting, adding/deleting events, and editable fields

2017-03-13 16:06 UTC, larajanecka requested changes

2017-03-13 16:06 UTC, larajanecka commented on src/js/pages/organizer/Calendar.jsx
> +    this.getEvents = this.getEvents.bind(this);
if possible we should be using fat arrow functions instead of binding.

2017-03-13 16:06 UTC, larajanecka commented on src/js/pages/organizer/Calendar.jsx
> +    EventStore.on("received", this.getEvents);
should probably also have a listener for errors, in case we decide to do for reals error handling in the future.

2017-03-13 16:06 UTC, larajanecka commented on src/js/stores/EventStore.jsx
> +        console.log(response);
These should be dispatching events for the action handler. How has the page been updating without that? I guess if we are doing lazy updates, thats fine.

2017-03-13 16:06 UTC, larajanecka commented on src/js/pages/organizer/Calendar.jsx
> +        <TableHeaderColumn dataField='name' dataSort filter={ { type: 'TextFilter', delay: 100 } }>
should this be 1000 like the others or is it intentionally a tenth of a second?

2017-03-13 23:16 UTC, schneider-clarisse commented on src/js/pages/organizer/Calendar.jsx
> +        <TableHeaderColumn dataField='name' dataSort filter={ { type: 'TextFilter', delay: 100 } }>
oh that was intentional i need to change the others good catch (y)

2017-03-13 23:17 UTC, schneider-clarisse commented on src/js/stores/EventStore.jsx
> +        console.log(response);
I think we're good for lazy updates here, the table just caches stuff anyways

2017-03-13 23:17 UTC, schneider-clarisse commented on src/js/pages/organizer/Calendar.jsx
> +    EventStore.on("received", this.getEvents);
(y)

2017-03-13 23:17 UTC, schneider-clarisse commented on src/js/pages/organizer/Calendar.jsx
> +    this.getEvents = this.getEvents.bind(this);
how so?

2017-03-13 23:18 UTC, larajanecka commented on src/js/pages/organizer/Calendar.jsx
> +        <TableHeaderColumn dataField='name' dataSort filter={ { type: 'TextFilter', delay: 100 } }>
gotcha

2017-03-13 23:19 UTC, larajanecka commented on src/js/stores/EventStore.jsx
> +        console.log(response);
I'm just worried this is going to become common practice and then we run into caching problems.

2017-03-13 23:19 UTC, schneider-clarisse commented on src/js/pages/organizer/Calendar.jsx
> +    this.getEvents = this.getEvents.bind(this);
offline chat clarified (y)

2017-03-13 23:25 UTC, larajanecka commented on src/js/pages/organizer/Calendar.jsx
> +    console.log(EventStore.error)
feel free to not do this, I'm trying to migrate us towards console.error.

2017-03-13 23:26 UTC, larajanecka approved these changes

2017-03-14 02:39 UTC, schneider-clarisse commented on src/js/stores/EventStore.jsx
> +        console.log(response);
talked offline, chatted about the table randomly updating as you're updating and decided to keep lazy loading.

2017-03-14 16:13 UTC, merged